/* =========================================================
   JOGOS DA PALAVRA — banco de perguntas compartilhado
   514 perguntas: 160 fáceis, 169 médias, 185 difíceis.

   Formato:  n = nível (1 fácil, 2 médio, 3 difícil)
             p = pergunta
             o = alternativas
             c = posição da alternativa certa, contando do zero
             r = referência bíblica

   Para acrescentar, copie uma linha e troque o conteúdo.
   Para corrigir um gabarito, mude o número em c.
   perguntas.js v2.0.0
   ========================================================= */
"use strict";

const PERGUNTAS = [

/* ---------- NÍVEL 1 — FÁCIL ---------- */
{n:1,p:"Quem construiu a arca?",o:["Abraão","Noé","Moisés","Jó"],c:1,r:"Gênesis 6:14"},
{n:1,p:"Por quantos dias e noites choveu no dilúvio?",o:["7","12","40","70"],c:2,r:"Gênesis 7:12"},
{n:1,p:"Qual é o primeiro livro da Bíblia?",o:["Êxodo","Gênesis","Salmos","João"],c:1,r:"Gênesis 1:1"},
{n:1,p:"Qual é o último livro da Bíblia?",o:["Judas","Apocalipse","Malaquias","Hebreus"],c:1,r:"Apocalipse 1:1"},
{n:1,p:"Quem foi lançado na cova dos leões?",o:["Daniel","Jeremias","Elias","Josué"],c:0,r:"Daniel 6:16"},
{n:1,p:"Em que cidade Jesus nasceu?",o:["Nazaré","Jerusalém","Belém","Cafarnaum"],c:2,r:"Mateus 2:1"},
{n:1,p:"Quem batizou Jesus no rio Jordão?",o:["Pedro","João Batista","André","Simeão"],c:1,r:"Mateus 3:13"},
{n:1,p:"Quantos discípulos Jesus escolheu?",o:["7","10","12","70"],c:2,r:"Marcos 3:14"},
{n:1,p:"Qual discípulo negou Jesus três vezes?",o:["Tomé","Pedro","Tiago","Filipe"],c:1,r:"Mateus 26:75"},
{n:1,p:"Qual mar se abriu para Israel na saída do Egito?",o:["Mar Morto","Mar da Galileia","Mar Vermelho","Mar Mediterrâneo"],c:2,r:"Êxodo 14:21"},
{n:1,p:"Quantos mandamentos Deus deu a Moisés no Sinai?",o:["7","10","12","40"],c:1,r:"Êxodo 20:1-17"},
{n:1,p:"Quem matou o gigante Golias?",o:["Saul","Jônatas","Davi","Sansão"],c:2,r:"1 Samuel 17:50"},
{n:1,p:"Qual era a profissão de Pedro antes de seguir Jesus?",o:["Carpinteiro","Pescador","Publicano","Tecelão"],c:1,r:"Mateus 4:18"},
{n:1,p:"Quem foi engolido por um grande peixe?",o:["Jonas","Oseias","Amós","Naum"],c:0,r:"Jonas 1:17"},
{n:1,p:"Qual era o nome da mãe de Jesus?",o:["Marta","Isabel","Maria","Ana"],c:2,r:"Lucas 1:27"},
{n:1,p:"Em quantos dias Deus fez a obra da criação, antes de descansar?",o:["3","6","7","12"],c:1,r:"Gênesis 1:31 e 2:2"},
{n:1,p:"Quem foi o primeiro homem?",o:["Caim","Enoque","Adão","Sete"],c:2,r:"Gênesis 2:7"},
{n:1,p:"Qual foi o primeiro milagre de Jesus, em Caná?",o:["Curou um cego","Transformou água em vinho","Andou sobre o mar","Multiplicou os pães"],c:1,r:"João 2:11"},
{n:1,p:"Quantos livros tem a Bíblia?",o:["39","27","66","72"],c:2,r:"39 no Antigo e 27 no Novo Testamento"},
{n:1,p:"Por quantas moedas de prata Judas traiu Jesus?",o:["10","20","30","50"],c:2,r:"Mateus 26:15"},
{n:1,p:"Qual era o nome do jardim onde Adão e Eva viveram?",o:["Getsêmani","Éden","Sarom","Carmelo"],c:1,r:"Gênesis 2:8"},
{n:1,p:"Quem sucedeu Moisés na liderança de Israel?",o:["Arão","Calebe","Josué","Gideão"],c:2,r:"Josué 1:1-2"},
{n:1,p:"De qual cidade as muralhas caíram depois que Israel a rodeou?",o:["Ai","Jericó","Hebrom","Siquém"],c:1,r:"Josué 6:20"},
{n:1,p:"Quem era o irmão de Moisés?",o:["Arão","Jetro","Corá","Nadabe"],c:0,r:"Êxodo 4:14"},
{n:1,p:"Qual foi o sinal da aliança de Deus com Noé?",o:["Uma estrela","O arco-íris","Uma pomba","Uma coluna de fogo"],c:1,r:"Gênesis 9:13"},
{n:1,p:"Qual foi o filho prometido a Abraão e Sara?",o:["Ismael","Jacó","Isaque","Esaú"],c:2,r:"Gênesis 21:3"},
{n:1,p:"Qual discípulo duvidou da ressurreição até ver as marcas?",o:["Tomé","Bartolomeu","Tadeu","André"],c:0,r:"João 20:25"},
{n:1,p:"Qual rei de Israel ficou conhecido por sua sabedoria?",o:["Davi","Salomão","Ezequias","Josias"],c:1,r:"1 Reis 3:12"},
{n:1,p:"Onde Jesus foi crucificado?",o:["Getsêmani","Betânia","Gólgota","Monte das Oliveiras"],c:2,r:"João 19:17"},
{n:1,p:"Quem era o pai de Salomão?",o:["Saul","Davi","Jessé","Absalão"],c:1,r:"2 Samuel 12:24"},
{n:1,p:"Quem foi o pai de Caim?",o:["Nun","Terá","Jacó","Adão"],c:3,r:"Gênesis 4:1"},
{n:1,p:"Quem foi o pai de Isaque?",o:["Terá","Abraão","Amoz","Adão"],c:1,r:"Gênesis 21:3"},
{n:1,p:"Quem foi o pai de Jacó?",o:["Nun","Terá","Amoz","Isaque"],c:3,r:"Gênesis 25:26"},
{n:1,p:"Quem foi o pai de José?",o:["Jacó","Isaque","Adão","Nun"],c:0,r:"Gênesis 30:24"},
{n:1,p:"Quem foi o pai de Davi?",o:["Zebedeu","Adão","Terá","Jessé"],c:3,r:"1 Samuel 16:11"},
{n:1,p:"Quem foi o pai de Sansão?",o:["Nun","Adão","Terá","Manoá"],c:3,r:"Juízes 13:24"},
{n:1,p:"Quem foi o pai de Abraão?",o:["Amoz","Adão","Manoá","Terá"],c:3,r:"Gênesis 11:27"},
{n:1,p:"Quem foi o pai de Tiago?",o:["Isaque","Lameque","Zebedeu","Abraão"],c:2,r:"Mateus 4:21"},
{n:1,p:"Quem foi o pai de Josué?",o:["Amoz","Nun","Adão","Abraão"],c:1,r:"Josué 1:1"},
{n:1,p:"Quem foi o pai de Isaías?",o:["Zebedeu","Nun","Manoá","Amoz"],c:3,r:"Isaías 1:1"},
{n:1,p:"Quem foi o marido de Eva?",o:["Elcana","Adão","Moisés","Assuero"],c:1,r:"Gênesis 4:1"},
{n:1,p:"Quem foi o marido de Sara?",o:["Adão","Zacarias","Ananias","Abraão"],c:3,r:"Gênesis 11:29"},
{n:1,p:"Quem foi o marido de Rebeca?",o:["Zacarias","Isaque","Ananias","Assuero"],c:1,r:"Gênesis 24:67"},
{n:1,p:"Quem foi o marido de Raquel?",o:["Isaque","Elcana","Ananias","Jacó"],c:3,r:"Gênesis 29:28"},
{n:1,p:"Quem foi o marido de Maria?",o:["Isaque","Boaz","Moisés","José"],c:3,r:"Mateus 1:24"},
{n:1,p:"Quem foi o marido de Rute?",o:["Zacarias","Adão","Boaz","Abraão"],c:2,r:"Rute 4:13"},
{n:1,p:"Quem foi o marido de Isabel?",o:["Zacarias","Isaque","Boaz","Adão"],c:0,r:"Lucas 1:5"},
{n:1,p:"Quem foi o marido de Ester?",o:["Moisés","Jacó","José","Assuero"],c:3,r:"Ester 2:17"},
{n:1,p:"Quem foi o marido de Zípora?",o:["Moisés","Elcana","Zacarias","Jacó"],c:0,r:"Êxodo 2:21"},
{n:1,p:"Quem foi o marido de Priscila?",o:["Zacarias","Áquila","Abraão","Isaque"],c:1,r:"Atos 18:2"},
{n:1,p:"Quem foi o marido de Safira?",o:["Áquila","Jacó","Isaque","Ananias"],c:3,r:"Atos 5:1"},
{n:1,p:"Quem foi o marido de Ana?",o:["José","Jacó","Boaz","Elcana"],c:3,r:"1 Samuel 1:2"},
{n:1,p:"Qual era a ocupação de Mateus?",o:["Pescador","Pastor de ovelhas","Médico","Cobrador de impostos"],c:3,r:"Mateus 9:9"},
{n:1,p:"Qual era a ocupação de Lucas?",o:["Médico","Cobrador de impostos","Pescadores","Agricultor"],c:0,r:"Colossenses 4:14"},
{n:1,p:"Qual era a ocupação de Pedro?",o:["Cobrador de impostos","Copeiro do rei","Pescador","Governador"],c:2,r:"Mateus 4:18"},
{n:1,p:"Qual era a ocupação de José (pai terreno de Jesus)?",o:["Agricultor","Cobrador de impostos","Carpinteiro","Escriba"],c:2,r:"Mateus 13:55"},
{n:1,p:"Qual era a ocupação de Davi (na juventude)?",o:["Pastor de ovelhas","Pescadores","Governador","Fazedor de tendas"],c:0,r:"1 Samuel 16:11"},
{n:1,p:"Qual era a ocupação de Caim?",o:["Agricultor","Escriba","Pescador","Médico"],c:0,r:"Gênesis 4:2"},
{n:1,p:"Qual era a ocupação de Paulo?",o:["Médico","Pescador","Escriba","Fazedor de tendas"],c:3,r:"Atos 18:3"},
{n:1,p:"Qual era a ocupação de Neemias?",o:["Governador","Pescador","Copeiro do rei","Escriba"],c:2,r:"Neemias 1:11"},
{n:1,p:"Qual era a ocupação de Abel?",o:["Cobrador de impostos","Copeiro do rei","Governador","Pastor de ovelhas"],c:3,r:"Gênesis 4:2"},
{n:1,p:"Qual era a ocupação de Esdras?",o:["Agricultor","Escriba","Fazedor de tendas","Pescador"],c:1,r:"Esdras 7:6"},
{n:1,p:"Qual era a ocupação de José (no Egito)?",o:["Médico","Governador","Agricultor","Pescadores"],c:1,r:"Gênesis 41:41"},
{n:1,p:"Qual era a ocupação de João e Tiago?",o:["Fazedor de tendas","Agricultor","Pescadores","Governador"],c:2,r:"Mateus 4:21"},
{n:1,p:"Em qual local Jesus nasceu?",o:["Belém","Jardim do Éden","Jerusalém","Damasco"],c:0,r:"Mateus 2:1"},
{n:1,p:"Em qual local Jesus cresceu?",o:["Rio Jordão","Nazaré","Damasco","Jerusalém"],c:1,r:"Mateus 2:23"},
{n:1,p:"Em qual local José foi vendido como escravo?",o:["Egito","Nazaré","Nínive","Monte Ararate"],c:0,r:"Gênesis 37:36"},
{n:1,p:"Em qual local as muralhas caíram?",o:["Jerusalém","Belém","Nazaré","Jericó"],c:3,r:"Josué 6:20"},
{n:1,p:"Em qual local Deus deu os 10 Mandamentos?",o:["Egito","Belém","Monte Sinai","Monte Ararate"],c:2,r:"Êxodo 19:20"},
{n:1,p:"Em qual local Adão e Eva viveram no início?",o:["Monte Sinai","Monte Ararate","Rio Jordão","Jardim do Éden"],c:3,r:"Gênesis 2:8"},
{n:1,p:"Em qual local Moisés abriu as águas?",o:["Mar Vermelho","Monte Sinai","Monte Ararate","Egito"],c:0,r:"Êxodo 14:21"},
{n:1,p:"Em qual local Jesus foi batizado?",o:["Belém","Mar Vermelho","Rio Jordão","Monte Ararate"],c:2,r:"Mateus 3:13"},
{n:1,p:"Em qual local Deus mandou Jonas pregar?",o:["Jerusalém","Jardim do Éden","Nínive","Monte Ararate"],c:2,r:"Jonas 1:2"},
{n:1,p:"Em qual local a arca de Noé repousou?",o:["Egito","Mar Vermelho","Jardim do Éden","Monte Ararate"],c:3,r:"Gênesis 8:4"},
{n:1,p:"Em qual local Salomão construiu o templo?",o:["Jerusalém","Rio Jordão","Belém","Monte Sinai"],c:0,r:"1 Reis 6:1"},
{n:1,p:"Em qual local Saulo ia quando teve a visão?",o:["Jerusalém","Rio Jordão","Damasco","Mar Vermelho"],c:2,r:"Atos 9:3"},
{n:1,p:"Qual ave Noé soltou para ver se as águas tinham baixado?",o:["Urso","Serpente","Galo","Pomba"],c:3,r:"Gênesis 8:8"},
{n:1,p:"Qual animal aparece na história de Daniel na cova?",o:["Leão","Jumenta","Galo","Grande Peixe"],c:0,r:"Daniel 6:16"},
{n:1,p:"Qual animal engoliu Jonas?",o:["Grande Peixe","Ovelha","Leão","Jumenta"],c:0,r:"Jonas 1:17"},
{n:1,p:"Qual animal aparece na parábola da ovelha perdida?",o:["Jumenta","Ovelha","Leão","Grande Peixe"],c:1,r:"Lucas 15:4"},
{n:1,p:"Quais aves levaram pão a Elias?",o:["Urso","Camelo","Corvos","Águia"],c:2,r:"1 Reis 17:6"},
{n:1,p:"Qual animal enganou Eva no Éden?",o:["Leão","Grande Peixe","Ovelha","Serpente"],c:3,r:"Gênesis 3:1"},
{n:1,p:"Qual animal cantou depois que Pedro negou Jesus?",o:["Grande Peixe","Galo","Leão","Serpente"],c:1,r:"Mateus 26:74"},
{n:1,p:"Sobre qual animal Jesus entrou em Jerusalém?",o:["Galo","Jumentinho","Urso","Cordeiro"],c:1,r:"Mateus 21:7"},
{n:1,p:"Quais animais Davi enfrentou defendendo o rebanho?",o:["Jumenta","Urso e Leão","Bode","Grande Peixe"],c:1,r:"1 Samuel 17:34"},
{n:1,p:"Que imagem de animal Arão fez no deserto?",o:["Bezerro de ouro","Samuel","Esaú","Josué"],c:0,r:"Êxodo 32:4"},
{n:1,p:"Para quais animais os demônios foram enviados em Gadara?",o:["Pomba","Bode","Porcos","Águia"],c:2,r:"Marcos 5:13"},
{n:1,p:"Qual animal falou com Balaão?",o:["Grande Peixe","Galo","Serpente","Jumenta"],c:3,r:"Números 22:28"},
{n:1,p:"Qual cego Jesus curou à saída de Jericó?",o:["Bartimeu","Tomé","Gamaliel","José"],c:0,r:"Marcos 10:46"},
{n:1,p:"Qual leproso foi curado ao mergulhar no Jordão?",o:["Naamã","Cornélio","Sete","Labão"],c:0,r:"2 Reis 5:14"},
{n:1,p:"Quem Jesus curou de febre na casa de Pedro?",o:["Neemias","Sogra de Pedro","Ananias","Eliseu"],c:1,r:"Mateus 8:14"},
{n:1,p:"Qual menina Jesus ressuscitou?",o:["Paulo","Salomão","Labão","Filha de Jairo"],c:3,r:"Marcos 5:22"},
{n:1,p:"Quem Jesus ressuscitou depois de quatro dias no sepulcro?",o:["Lázaro","Lucas","Moisés","Labão"],c:0,r:"João 11:39"},
{n:1,p:"Qual paralítico Jesus curou junto ao tanque de Betesda?",o:["Sete","Cornélio","José","Homem de Betesda"],c:3,r:"João 5:5"},
{n:1,p:"Quem foi curada ao tocar na orla do manto de Jesus?",o:["Boaz","A mulher","Rute","Zacarias"],c:1,r:"Marcos 5:25"},
{n:1,p:"De quem Jesus curou a orelha cortada por Pedro?",o:["Josué","Samuel","Maria Madalena","Malco"],c:3,r:"Lucas 22:50"},
{n:1,p:"Quantos leprosos Jesus curou de uma só vez, dos quais só um voltou?",o:["Dez homens","Josué","Ló","Sete"],c:0,r:"Lucas 17:12"},
{n:1,p:"Qual mulher pediu a Jesus a cura da filha endemoninhada?",o:["Raabe","Mulher cananeia","Abigail","Débora"],c:1,r:"Mateus 15:22"},
{n:1,p:"Quem Jesus ressuscitou no caminho de Naim?",o:["André","Cornélio","Filho da viúva de Naim","Natã"],c:2,r:"Lucas 7:14"},
{n:1,p:"Quantos mandamentos Deus deu a Moisés?",o:["Três","Dez","Cinco","Quatro"],c:1,r:"Êxodo 20:1"},
{n:1,p:"Quantas eram as tribos de Israel?",o:["Três","Cinco","Quatro","Doze"],c:3,r:"Gênesis 49:28"},
{n:1,p:"Em quantos dias Deus fez a obra da criação?",o:["Cinco","Seis","Três","Quatro"],c:1,r:"Gênesis 1:31"},
{n:1,p:"Ao terceiro dia Jesus ressuscitou; quantos dias esteve no sepulcro?",o:["Três","Quatro","Cinco","Seis"],c:0,r:"Lucas 24:7"},
{n:1,p:"Quantos pães e peixes Jesus multiplicou para os cinco mil?",o:["Cinco e Dois","Noé","Sete","Paulo"],c:0,r:"Mateus 14:17"},
{n:1,p:"Quantas vezes Pedro negou Jesus?",o:["Seis","Três","Quatro","Cinco"],c:1,r:"Mateus 26:75"},
{n:1,p:"Por quantas moedas de prata Judas entregou Jesus?",o:["Trinta","Quatro","Três","Cinco"],c:0,r:"Mateus 26:15"},
{n:1,p:"Quantas vezes Israel rodeou Jericó no sétimo dia?",o:["Cinco","Quatro","Sete","Três"],c:2,r:"Josué 6:4"},
{n:1,p:"Quantos anos Israel andou pelo deserto?",o:["Três","Quarenta","Cinco","Quatro"],c:1,r:"Josué 5:6"},
{n:1,p:"Quantas vezes Naamã mergulhou no Jordão?",o:["Sete","Três","Cinco","Quatro"],c:0,r:"2 Reis 5:14"},
{n:1,p:"Quem O homem mais forte da Bíblia?",o:["Silas","Salomão","Sansão","Jônatas"],c:2,r:"Juízes 14:6"},
{n:1,p:"Quem Pediu sabedoria a Deus?",o:["Salomão","Ananias","Eliseu","Mateus"],c:0,r:"1 Reis 3:9"},
{n:1,p:"Quem Libertou Israel do Egito?",o:["Moisés","Apolo","Gamaliel","Natã"],c:0,r:"Êxodo 3:10"},
{n:1,p:"Quem Foi a primeira mulher?",o:["Jael","Filha de Herodias (Salomé)","Rute","Eva"],c:3,r:"Gênesis 3:20"},
{n:1,p:"Quem O discípulo que traiu Jesus?",o:["Sete","Judas","Apolo","Josué"],c:1,r:"Lucas 22:47"},
{n:1,p:"Quem Andou sobre as águas?",o:["Timóteo","Calebe","Eliseu","Pedro"],c:3,r:"Mateus 14:29"},
{n:1,p:"Quem Batizou Jesus?",o:["Arão","João Batista","Silas","Boaz"],c:1,r:"Mateus 3:13"},
{n:1,p:"Quem Anjo que anunciou a Maria?",o:["Filipe","Gabriel","Silas","Apolo"],c:1,r:"Lucas 1:26"},
{n:1,p:"Quem Lavou as mãos na morte de Jesus?",o:["Jônatas","Filipe","Boaz","Pilatos"],c:3,r:"Mateus 27:24"},
{n:1,p:"O que Moisés estendeu sobre o mar para abri-lo?",o:["Cântaros e tochas","Cajado","Abraão foi sacrificar Isaque","Os samaritanos adoravam"],c:1,r:"Êxodo 14:16"},
{n:1,p:"O que Davi usou para derrotar Golias?",o:["Abraão foi sacrificar Isaque","Coroa de espinhos","Os samaritanos adoravam","Funda e pedra"],c:3,r:"1 Samuel 17:50"},
{n:1,p:"Com que arma Sansão matou mil filisteus?",o:["Espada","30 anos","12 anos","Queixada de jumento"],c:3,r:"Juízes 15:15"},
{n:1,p:"O que Jesus usou para curar o cego de nascença?",o:["Estrela","Quatro bestas","Lodo (barro)","Cajado"],c:2,r:"João 9:6"},
{n:1,p:"Com que a mulher pecadora ungiu os pés de Jesus?",o:["Queixada de jumento","30 anos","Perfume","12 anos"],c:2,r:"Lucas 7:37"},
{n:1,p:"O que a viúva pobre ofertou no templo?",o:["Duas moedinhas","Estrela","Jesus foi crucificado","Abraão foi sacrificar Isaque"],c:0,r:"Lucas 21:2"},
{n:1,p:"De que madeira Noé fez a arca?",o:["Perfume","Punhado de farinha","Odres de vinho","Madeira de gofer"],c:3,r:"Gênesis 6:14"},
{n:1,p:"O que os homens de Gideão levaram na batalha?",o:["Estátua de 4 metais e barro","Moisés avistou a Terra Prometida e morreu","Abraão foi sacrificar Isaque","Cântaros e tochas"],c:3,r:"Juízes 7:16"},
{n:1,p:"Com que Pedro cortou a orelha de Malco?",o:["12 anos","30 anos","Espada","Queixada de jumento"],c:2,r:"João 18:10"},
{n:1,p:"Em que os discípulos desceram Paulo pelo muro?",o:["Éfeso","Gólgota (Calvário)","Carmelo","Cesto"],c:3,r:"Atos 9:25"},
{n:1,p:"O que os magos seguiram até chegar a Jesus?",o:["Cântaros e tochas","Cajado","Estrela","Quatro bestas"],c:2,r:"Mateus 2:2"},
{n:1,p:"O que os soldados puseram na cabeça de Jesus?",o:["Jesus orou antes de ser preso (Getsêmani)","Abraão foi sacrificar Isaque","Coroa de espinhos","Deus deu os Dez Mandamentos"],c:2,r:"Marcos 15:17"},
{n:1,p:"Quem era irmão de Pedro?",o:["Esaú","João","André","Abel"],c:2,r:"Mateus 4:18"},
{n:1,p:"Quem era irmão de Tiago?",o:["Abel","André","Esaú","João"],c:3,r:"Mateus 4:21"},
{n:1,p:"Quem era irmão de Caim?",o:["João","Esaú","Abel","André"],c:2,r:"Gênesis 4:2"},
{n:1,p:"Quem era irmão de Jacó?",o:["André","Abel","João","Esaú"],c:3,r:"Gênesis 25:25"},
{n:1,p:"Qual era o irmão mais novo de José?",o:["Fazedores de tendas","Benjamim","Esaú","Jessé"],c:1,r:"Gênesis 43:29"},
{n:1,p:"Quem era o irmão de Marta e Maria?",o:["Arão","Judas (não Iscariotes)","Jônatas","Lázaro"],c:3,r:"João 11:1-2"},
{n:1,p:"Quem era o meio-irmão de Isaque?",o:["Ismael","Davi","Lázaro","Filemom"],c:0,r:"Gênesis 16:15"},
{n:1,p:"Quem era a irmã de Moisés e Arão?",o:["Raquel","Diana (Ártemis)","Miriã","Maria"],c:2,r:"Números 26:59"},
{n:1,p:"Quem era a irmã de Lia?",o:["Diana (Ártemis)","Raquel","Miriã","Maria"],c:1,r:"Gênesis 29:16"},
{n:1,p:"Qual era a irmã dos filhos de Jacó?",o:["Pescador","Copeiro do rei","Dina","Fazedor de tendas"],c:2,r:"Gênesis 30:21"},
{n:1,p:"Quem era o irmão de Mical?",o:["Lázaro","Jônatas","Arão","Judas (não Iscariotes)"],c:1,r:"1 Samuel 14:49"},
{n:1,p:"Onde Jesus nasceu?",o:["Eliseu","Belém","Noé","Apolo"],c:1,r:"Mateus 2:1"},
{n:1,p:"Quem era a mãe de Jesus?",o:["Diana (Ártemis)","Raquel","Miriã","Maria"],c:3,r:"Lucas 1:27"},
{n:1,p:"Quem traiu Jesus?",o:["Apolo","Judas Iscariotes","Tomé","Timóteo"],c:1,r:"Mateus 26:14-16"},
{n:1,p:"Quantos dias durou a criação do mundo?",o:["6 dias","9 dias","7 dias","12 dias"],c:0,r:"Gênesis 1"},
{n:1,p:"Quem foi o primeiro homem criado por Deus?",o:["Otniel","Adão","Estêvão","Saul"],c:1,r:"Gênesis 2:7"},
{n:1,p:"Quem abriu o Mar Vermelho pelo poder de Deus?",o:["Filipe","Esaú","João","Moisés"],c:3,r:"Êxodo 14:21"},
{n:1,p:"Quantas pragas Deus enviou ao Egito?",o:["André","Gideão","Dez pragas","Marcos"],c:2,r:"Êxodo 7 a 12"},
{n:1,p:"Como se chamava o jardim onde Adão e Eva moravam?",o:["Jardim do Éden","Neemias","André","Josué"],c:0,r:"Gênesis 2:8"},
{n:1,p:"Em qual rio Jesus foi batizado?",o:["Rio Jordão","Jardim do Éden","Monte Ararate","Parábola dos Talentos"],c:0,r:"Mateus 3:13"},
{n:1,p:"Qual era a profissão de Pedro?",o:["Pastor de ovelhas","Governador","Agricultor","Pescador"],c:3,r:"Mateus 4:18"},
{n:1,p:"Quem chorou amargamente após negar Jesus?",o:["Mateus","André","Pedro","Marcos"],c:2,r:"Mateus 26:75"},
{n:1,p:"Qual rei de Israel pediu sabedoria a Deus?",o:["Ezequias","Acabe","Zinri","Salomão"],c:3,r:"1 Reis 3:9"},
{n:1,p:"Quem ganhou uma túnica colorida de seu pai?",o:["Joabe","Jônatas","José","Arão"],c:2,r:"Gênesis 37:3"},
{n:1,p:"Quem foi vendido como escravo pelos irmãos?",o:["José","Simão Cireneu","Nun","Jael"],c:0,r:"Gênesis 37:28"},
{n:1,p:"Quem era conhecido por sua grande força?",o:["Sansão","Diana (Ártemis)","Anás","Naassom"],c:0,r:"Juízes 14:6"},
{n:1,p:"Qual menino ouviu a voz de Deus no templo?",o:["Timóteo","Ananias","Esaú","Samuel"],c:3,r:"1 Samuel 3:4"},
{n:1,p:"Quem subiu ao céu em um redemoinho?",o:["Ló","Elias","Absalão","Filipe"],c:1,r:"2 Reis 2:11"},
{n:1,p:"Em que cidade os muros caíram após o povo gritar?",o:["Sarepta","Jericó","Éfeso","Belém"],c:1,r:"Josué 6:20"},
{n:1,p:"Qual homem andou sobre as águas com Jesus?",o:["Zorobabel","Absalão","Pedro","Natã"],c:2,r:"Mateus 14:29"},

/* ---------- NÍVEL 2 — MÉDIO ---------- */
{n:2,p:"Quem era o sogro de Moisés?",o:["Labão","Jetro","Naasom","Hur"],c:1,r:"Êxodo 3:1"},
{n:2,p:"Quantos anos Israel peregrinou no deserto?",o:["7","12","40","70"],c:2,r:"Números 14:33"},
{n:2,p:"Qual profeta foi levado ao céu num carro de fogo?",o:["Eliseu","Elias","Enoque","Isaías"],c:1,r:"2 Reis 2:11"},
{n:2,p:"Quem acompanhou Paulo na primeira viagem missionária?",o:["Silas","Timóteo","Barnabé","Tito"],c:2,r:"Atos 13:2-3"},
{n:2,p:"Qual nome os babilônios deram a Daniel?",o:["Beltessazar","Sadraque","Abede-Nego","Mesaque"],c:0,r:"Daniel 1:7"},
{n:2,p:"Qual rainha arriscou a vida para salvar seu povo na Pérsia?",o:["Vasti","Ester","Mical","Betsabá"],c:1,r:"Ester 4:16"},
{n:2,p:"Quem escreveu o livro de Atos dos Apóstolos?",o:["Pedro","Paulo","Lucas","Marcos"],c:2,r:"Atos 1:1; Lucas 1:3"},
{n:2,p:"Quantos anos Jacó serviu no total para casar com Raquel?",o:["7","10","14","20"],c:2,r:"Gênesis 29:20-30"},
{n:2,p:"Qual era a profissão de Lucas?",o:["Médico","Advogado","Fabricante de tendas","Escriba"],c:0,r:"Colossenses 4:14"},
{n:2,p:"Quem foi o primeiro mártir cristão?",o:["Tiago","Estêvão","Barnabé","Filipe"],c:1,r:"Atos 7:59-60"},
{n:2,p:"Qual rei construiu o templo de Jerusalém?",o:["Davi","Salomão","Josias","Zorobabel"],c:1,r:"1 Reis 6:1"},
{n:2,p:"Quem era o pai de João Batista?",o:["Zacarias","Simeão","Eli","Ananias"],c:0,r:"Lucas 1:13"},
{n:2,p:"Em que monte Elias desafiou os profetas de Baal?",o:["Sinai","Nebo","Carmelo","Hermom"],c:2,r:"1 Reis 18:19-20"},
{n:2,p:"Em qual jardim Jesus orou antes de ser preso?",o:["Éden","Getsêmani","Betânia","Siloé"],c:1,r:"Mateus 26:36"},
{n:2,p:"Quem foi escolhido para substituir Judas entre os doze?",o:["Matias","Barsabás","Estêvão","Paulo"],c:0,r:"Atos 1:26"},
{n:2,p:"Qual profeta teve a visão do vale de ossos secos?",o:["Jeremias","Ezequiel","Daniel","Zacarias"],c:1,r:"Ezequiel 37:1-10"},
{n:2,p:"Qual governador romano julgou Jesus?",o:["Herodes","Félix","Pôncio Pilatos","Festo"],c:2,r:"Mateus 27:2"},
{n:2,p:"Qual era o nome do pai de Davi?",o:["Obede","Jessé","Boaz","Ner"],c:1,r:"1 Samuel 16:1"},
{n:2,p:"Qual mulher foi juíza em Israel?",o:["Ana","Débora","Rute","Hulda"],c:1,r:"Juízes 4:4"},
{n:2,p:"Quantos anos viveu Matusalém?",o:["777","895","930","969"],c:3,r:"Gênesis 5:27"},
{n:2,p:"Quem foi o primeiro rei de Israel?",o:["Davi","Saul","Samuel","Roboão"],c:1,r:"1 Samuel 10:1"},
{n:2,p:"Como Paulo se chamava antes de sua conversão?",o:["Silas","Saulo","Simeão","Sóstenes"],c:1,r:"Atos 13:9"},
{n:2,p:"Em que ilha João recebeu a revelação do Apocalipse?",o:["Creta","Chipre","Patmos","Malta"],c:2,r:"Apocalipse 1:9"},
{n:2,p:"Quem foi obrigado a carregar a cruz de Jesus?",o:["José de Arimateia","Simão Cireneu","Nicodemos","Barrabás"],c:1,r:"Marcos 15:21"},
{n:2,p:"Qual era o nome da irmã de Moisés?",o:["Miriã","Zípora","Débora","Jocabede"],c:0,r:"Êxodo 15:20"},
{n:2,p:"Quantas pragas caíram sobre o Egito?",o:["7","10","12","40"],c:1,r:"Êxodo 7—12"},
{n:2,p:"Quem subiu numa árvore para conseguir ver Jesus?",o:["Nicodemos","Zaqueu","Bartimeu","Levi"],c:1,r:"Lucas 19:4"},
{n:2,p:"Qual profeta recebeu ordem de se casar com Gômer?",o:["Amós","Oseias","Miqueias","Joel"],c:1,r:"Oseias 1:3"},
{n:2,p:"Qual discípulo é chamado 'aquele a quem Jesus amava'?",o:["Pedro","João","Tiago","André"],c:1,r:"João 13:23"},
{n:2,p:"Qual era o nome do irmão mais velho de Jacó?",o:["Esaú","Labão","Levi","Judá"],c:0,r:"Gênesis 25:25"},
{n:2,p:"De quem Quis foi pai?",o:["Saul","Matusalém","Rebeca","Absalão"],c:0,r:"1 Samuel 9:1"},
{n:2,p:"De quem Elcana foi pai?",o:["Samuel","Malco","Beteuel","Miriã, Arão e Moisés"],c:0,r:"1 Samuel 1:20"},
{n:2,p:"De quem Um grego foi pai?",o:["De um israelita anônimo","Noé","Dina","Timóteo"],c:3,r:"Atos 16:1"},
{n:2,p:"De quem Davi foi pai?",o:["Eliseu","Timóteo","Rebeca","Absalão"],c:3,r:"2 Samuel 3:3"},
{n:2,p:"De quem Anrão foi pai?",o:["Miriã, Arão e Moisés","Matusalém","De um israelita anônimo","Beteuel"],c:0,r:"Números 26:59"},
{n:2,p:"De quem Jacó foi pai?",o:["Rebeca","Josué","Dina","Samuel"],c:2,r:"Gênesis 30:21"},
{n:2,p:"De quem Beteuel foi pai?",o:["Maria Madalena","Noé","Rebeca","Dina"],c:2,r:"Gênesis 22:23"},
{n:2,p:"De quem Safate foi pai?",o:["Samuel","Saul","Miriã, Arão e Moisés","Eliseu"],c:3,r:"1 Reis 19:16"},
{n:2,p:"De quem Lameque foi pai?",o:["Eliseu","Rebeca","Matusalém","Noé"],c:3,r:"Gênesis 5:28"},
{n:2,p:"De quem Enoque foi pai?",o:["Eliseu","Noé","Matusalém","Malco"],c:2,r:"Gênesis 5:21"},
{n:2,p:"De quem Nun foi pai?",o:["Josué","Beteuel","Matusalém","Eliseu"],c:0,r:"Josué 1:1"},
{n:2,p:"De quem Nacor foi pai?",o:["Samuel","Maria Madalena","Beteuel","Dina"],c:2,r:"Gênesis 22:20"},
{n:2,p:"Quem foi a mulher que escondeu os espias de Josué?",o:["Raabe","Ana","Filha de Herodias (Salomé)","Jael"],c:0,r:"Josué 2:1"},
{n:2,p:"Quem foi a mulher que matou Sísera com uma estaca?",o:["Jael","Raabe","Filha de Herodias (Salomé)","Ana"],c:0,r:"Juízes 4:21"},
{n:2,p:"Quem foi a mulher que foi profetisa e juíza de Israel?",o:["Filha de Herodias (Salomé)","Ana","Ester","Débora"],c:3,r:"Juízes 4:4"},
{n:2,p:"Quem foi a mulher que orou no templo chorando por um filho?",o:["Ester","Débora","Ana","Filha de Herodias (Salomé)"],c:2,r:"1 Samuel 1:10"},
{n:2,p:"Qual mulher foi casada com Nabal e depois com Davi?",o:["Débora","Abigail","Raabe","Mulher cananeia"],c:1,r:"1 Samuel 25:39"},
{n:2,p:"Quem foi a mulher que salvou os judeus do decreto de Hamã?",o:["Raabe","Jael","Ana","Ester"],c:3,r:"Ester 7:3"},
{n:2,p:"Quem foi a mulher que dançou para Herodes e pediu a cabeça de João Batista?",o:["Jael","Ana","Filha de Herodias (Salomé)","Ester"],c:2,r:"Mateus 14:6"},
{n:2,p:"Quem foi a esposa do profeta Oseias?",o:["Filha de Herodias (Salomé)","Gômer","Loide","Eva"],c:1,r:"Oseias 1:3"},
{n:2,p:"Qual irmã de Moisés cantou depois da travessia do mar?",o:["Abigail","Miriã","Isabel","Lia"],c:1,r:"Êxodo 15:20"},
{n:2,p:"Qual nora de Noemi voltou com ela de Moabe?",o:["Safira","Rute","Rebeca","Isabel"],c:1,r:"Rute 1:16"},
{n:2,p:"Qual profetisa viu o menino Jesus no templo?",o:["Raabe","Ana","Lia","Abigail"],c:1,r:"Lucas 2:36"},
{n:2,p:"Quem visitou Salomão para prová-lo com perguntas?",o:["Rainha de Sabá","Abraão","Josué","Pedro"],c:0,r:"1 Reis 10:1"},
{n:2,p:"Como morreu Golias?",o:["Lançada da janela e comida por cães","Por uma pedra e espada","Esmagado pelos pilares do templo","Morto pelo povo após conspirar"],c:1,r:"1 Samuel 17:50-51"},
{n:2,p:"Como morreu Absalão?",o:["Por uma pedra e espada","Esmagado pelos pilares do templo","Preso pelos cabelos na árvore","Morto à espada por Herodes"],c:2,r:"2 Samuel 18:9"},
{n:2,p:"Como morreu Judas Iscariotes?",o:["Decapitado na prisão","Enforcado","Apedrejado","Preso pelos cabelos na árvore"],c:1,r:"Mateus 27:5"},
{n:2,p:"Como morreu Estêvão?",o:["Apedrejado","Preso pelos cabelos na árvore","Por uma pedra e espada","Enforcado"],c:0,r:"Atos 7:59"},
{n:2,p:"Como morreu Tiago (irmão de João)?",o:["Morto pelo povo após conspirar","Morto à espada por Herodes","Caiu da cadeira e quebrou o pescoço","Por uma pedra e espada"],c:1,r:"Atos 12:2"},
{n:2,p:"Como morreu João Batista?",o:["Por uma pedra e espada","Morto à espada por Herodes","Decapitado na prisão","Morto pelo povo após conspirar"],c:2,r:"Mateus 14:10"},
{n:2,p:"Como morreu Jezabel?",o:["Lançada da janela e comida por cães","Caiu da cadeira e quebrou o pescoço","Morto à espada por Herodes","Por uma pedra e espada"],c:0,r:"2 Reis 9:33"},
{n:2,p:"Como morreu Sansão?",o:["Morto pelo povo após conspirar","Preso pelos cabelos na árvore","Lançada da janela e comida por cães","Esmagado pelos pilares do templo"],c:3,r:"Juízes 16:30"},
{n:2,p:"Como morreu Zacarias (rei de Israel)?",o:["Morto pelo povo após conspirar","Lançada da janela e comida por cães","Por uma pedra e espada","Decapitado na prisão"],c:0,r:"2 Reis 15:10"},
{n:2,p:"Como morreu Sacerdote Eli?",o:["Esmagado pelos pilares do templo","Preso pelos cabelos na árvore","Morto pelo povo após conspirar","Caiu da cadeira e quebrou o pescoço"],c:3,r:"1 Samuel 4:18"},
{n:2,p:"Em qual parábola O filho gastou tudo?",o:["Parábola do Bom Samaritano","Parábola do Filho Pródigo","Parábola do Rico Insensato","Parábola dos Talentos"],c:1,r:"Lucas 15:13"},
{n:2,p:"Em qual parábola Um homem ajudou um ferido?",o:["Parábola do Construtor Prudente","Parábola do Fariseu e Publicano","Parábola dos Talentos","Parábola do Bom Samaritano"],c:3,r:"Lucas 10:33"},
{n:2,p:"Em qual parábola A palavra de Deus é semente?",o:["Parábola do Construtor Prudente","Parábola do Joio","Parábola das Dez Virgens","Parábola do Semeador"],c:3,r:"Lucas 8:11"},
{n:2,p:"Em qual parábola Os servos recebem moedas?",o:["Parábola do Tesouro Escondido","Parábola dos Talentos","Parábola do Filho Pródigo","Parábola do Construtor Prudente"],c:1,r:"Mateus 25:15"},
{n:2,p:"Em qual parábola Uma mulher busca uma moeda?",o:["Parábola do Bom Samaritano","Parábola do Fariseu e Publicano","Parábola da Dracma Perdida","Parábola dos Talentos"],c:2,r:"Lucas 15:8"},
{n:2,p:"Em qual parábola O inimigo planta no meio do trigo?",o:["Parábola do Joio","Parábola do Rico Insensato","Parábola do Bom Samaritano","Parábola do Construtor Prudente"],c:0,r:"Mateus 13:25"},
{n:2,p:"Em qual parábola O pastor deixa as 99?",o:["Parábola do Filho Pródigo","Parábola da Dracma Perdida","Parábola do Semeador","Parábola da Ovelha Perdida"],c:3,r:"Lucas 15:4"},
{n:2,p:"Em qual parábola Cinco são prudentes e cinco néscias?",o:["Parábola do Fariseu e Publicano","Parábola do Rico Insensato","Parábola das Dez Virgens","Parábola do Tesouro Escondido"],c:2,r:"Mateus 25:2"},
{n:2,p:"Em qual parábola Dois homens oram no templo?",o:["Parábola da Ovelha Perdida","Parábola do Filho Pródigo","Parábola da Dracma Perdida","Parábola do Fariseu e Publicano"],c:3,r:"Lucas 18:10"},
{n:2,p:"Em qual parábola Constrói a casa na rocha?",o:["Parábola dos Talentos","Parábola do Joio","Parábola do Construtor Prudente","Parábola do Fariseu e Publicano"],c:2,r:"Mateus 7:24"},
{n:2,p:"Em qual parábola Guarda muito para si e morre?",o:["Parábola da Ovelha Perdida","Parábola do Rico Insensato","Parábola do Bom Samaritano","Parábola do Tesouro Escondido"],c:1,r:"Lucas 12:20"},
{n:2,p:"Em qual parábola Encontra no campo e compra?",o:["Parábola do Tesouro Escondido","Parábola dos Talentos","Parábola das Dez Virgens","Parábola do Semeador"],c:0,r:"Mateus 13:44"},
{n:2,p:"O que aconteceu no monte Sinai?",o:["Davi capturou a fortaleza e chamou Cidade de Davi","Deus deu os Dez Mandamentos","Deus falou na sarça ardente a Moisés","Os samaritanos adoravam"],c:1,r:"Êxodo 19:20"},
{n:2,p:"O que aconteceu no monte Carmelo?",o:["A arca de Noé repousou após o dilúvio","Moisés avistou a Terra Prometida e morreu","Elias desafiou os profetas de Baal","Os samaritanos adoravam"],c:2,r:"1 Reis 18:19"},
{n:2,p:"O que aconteceu no monte Moriá?",o:["Jesus orou antes de ser preso (Getsêmani)","Deus falou na sarça ardente a Moisés","Abraão foi sacrificar Isaque","Josué construiu um altar de pedras inteiras"],c:2,r:"Gênesis 22:2"},
{n:2,p:"O que aconteceu no monte Horebe?",o:["Josué construiu um altar de pedras inteiras","A arca de Noé repousou após o dilúvio","Jesus orou antes de ser preso (Getsêmani)","Deus falou na sarça ardente a Moisés"],c:3,r:"Êxodo 3:1-2"},
{n:2,p:"O que aconteceu no monte Hermom (ou Tabor)?",o:["Josué construiu um altar de pedras inteiras","Aconteceu a Transfiguração de Jesus","Davi capturou a fortaleza e chamou Cidade de Davi","Deus falou na sarça ardente a Moisés"],c:1,r:"Mateus 17:1"},
{n:2,p:"O que aconteceu no monte das Oliveiras?",o:["Jesus orou antes de ser preso (Getsêmani)","Davi capturou a fortaleza e chamou Cidade de Davi","Josué construiu um altar de pedras inteiras","Os samaritanos adoravam"],c:0,r:"Mateus 26:30"},
{n:2,p:"O que aconteceu no monte Ararate?",o:["A arca de Noé repousou após o dilúvio","Moisés avistou a Terra Prometida e morreu","Deus falou na sarça ardente a Moisés","Deus deu os Dez Mandamentos"],c:0,r:"Gênesis 8:4"},
{n:2,p:"O que aconteceu no monte Nebo?",o:["Aconteceu a Transfiguração de Jesus","A arca de Noé repousou após o dilúvio","Moisés avistou a Terra Prometida e morreu","Elias desafiou os profetas de Baal"],c:2,r:"Deuteronômio 34:1"},
{n:2,p:"O que aconteceu no monte Ebal?",o:["Abraão foi sacrificar Isaque","A arca de Noé repousou após o dilúvio","Josué construiu um altar de pedras inteiras","Elias desafiou os profetas de Baal"],c:2,r:"Josué 8:30"},
{n:2,p:"O que aconteceu no monte Sião?",o:["Davi capturou a fortaleza e chamou Cidade de Davi","A arca de Noé repousou após o dilúvio","Josué construiu um altar de pedras inteiras","Deus deu os Dez Mandamentos"],c:0,r:"2 Samuel 5:7"},
{n:2,p:"O que aconteceu no Gólgota?",o:["Elias desafiou os profetas de Baal","Jesus foi crucificado","Josué construiu um altar de pedras inteiras","Moisés avistou a Terra Prometida e morreu"],c:1,r:"João 19:17"},
{n:2,p:"O que aconteceu no monte Gerizim?",o:["Os samaritanos adoravam","Deus deu os Dez Mandamentos","Deus falou na sarça ardente a Moisés","Josué construiu um altar de pedras inteiras"],c:0,r:"João 4:20"},
{n:2,p:"Quantos anos durou o exílio dos judeus na Babilônia?",o:["70 anos","110 anos","140 anos","30 anos"],c:0,r:"Jeremias 29:10"},
{n:2,p:"Por quantos dias Jesus jejuou no deserto?",o:["40 dias","20 dias","41 dias","39 dias"],c:0,r:"Mateus 4:2"},
{n:2,p:"Com que idade Jesus começou seu ministério?",o:["20 anos","30 anos","60 anos","23 anos"],c:1,r:"Lucas 3:23"},
{n:2,p:"Com que idade Jesus ensinou os doutores no templo?",o:["6 anos","13 anos","12 anos","19 anos"],c:2,r:"Lucas 2:42"},
{n:2,p:"Há quantos anos a mulher sofria de hemorragia quando tocou em Jesus?",o:["24 anos","12 anos","9 anos","15 anos"],c:1,r:"Marcos 5:25"},
{n:2,p:"Há quantos anos o homem do tanque de Betesda estava enfermo?",o:["78 anos","41 anos","45 anos","38 anos"],c:3,r:"João 5:5"},
{n:2,p:"Com quantos homens Gideão enfrentou os midianitas?",o:["300 homens","260 homens","150 homens","310 homens"],c:0,r:"Juízes 7:7"},
{n:2,p:"Quantos anos foram acrescentados à vida de Ezequias?",o:["22 anos","25 anos","14 anos","15 anos"],c:3,r:"2 Reis 20:6"},
{n:2,p:"Com quantos dias de vida o menino israelita era circuncidado?",o:["7 dias","8 dias","9 dias","4 dias"],c:1,r:"Gênesis 17:12"},
{n:2,p:"Por quantos dias Golias desafiou o exército de Israel?",o:["40 dias","120 dias","33 dias","39 dias"],c:0,r:"1 Samuel 17:16"},
{n:2,p:"Quanto tempo ficou sem chover pela palavra de Elias?",o:["Ananias","3 anos e meio","Pedro","Sete"],c:1,r:"Tiago 5:17"},
{n:2,p:"Quantos anos de fome o sonho de Faraó anunciava?",o:["969","7 vacas magras","14","40"],c:1,r:"Gênesis 41:27"},
{n:2,p:"Qual rei começou a reinar aos oito anos e achou o Livro da Lei?",o:["Rei Asa","Herodes, o Grande","Atalia","Josias"],c:3,r:"2 Reis 22:1"},
{n:2,p:"Qual rei virou animal por sete tempos?",o:["Acabe","Nabucodonosor","Hoshea (Oseias)","Menaém"],c:1,r:"Daniel 4:33"},
{n:2,p:"Qual rei viu a mão escrever na parede?",o:["Nabucodonosor","Assuero","Belsazar","Herodes, o Grande"],c:2,r:"Daniel 5:5"},
{n:2,p:"Qual rei roubou a vinha de Nabote?",o:["Salomão","Acabe","Ciro","Joás"],c:1,r:"1 Reis 21:16"},
{n:2,p:"Qual rei fez bezerros de ouro em Dan e Betel?",o:["Assuero","Ezequias","Jeroboão","Zinri"],c:2,r:"1 Reis 12:28"},
{n:2,p:"Qual rei causou a divisão do reino após Salomão?",o:["Herodes","Roboão","Ezequias","Acabe"],c:1,r:"1 Reis 12:16"},
{n:2,p:"Qual rei mandou matar os meninos em Belém?",o:["Zedequias","Herodes, o Grande","Rei Asa","Eglom"],c:1,r:"Mateus 2:16"},
{n:2,p:"Qual rei da Pérsia que casou com Ester?",o:["Assuero","Uzias","Herodes, o Grande","Nabucodonosor"],c:0,r:"Ester 2:17"},
{n:2,p:"Qual rei teve 700 esposas e 300 concubinas?",o:["Eglom","Herodes, o Grande","Salomão","Zinri"],c:2,r:"1 Reis 11:3"},
{n:2,p:"Qual rei adoeceu dos pés na velhice e não buscou ao Senhor?",o:["Asa","Onri","Herodes, o Grande","Belsazar"],c:0,r:"2 Crônicas 16:12"},
{n:2,p:"Qual rei ficou leproso ao queimar incenso?",o:["Nabucodonosor","Manassés","Uzias","Roboão"],c:2,r:"2 Crônicas 26:19"},
{n:2,p:"Qual rei da Pérsia que permitiu os judeus voltarem?",o:["Herodes, o Grande","Menaém","Ciro","Acabe"],c:2,r:"Esdras 1:1"},
{n:2,p:"Qual profeta fez o machado flutuar na água?",o:["Oseias","Ágabo","Obadias","Eliseu"],c:3,r:"2 Reis 6:6"},
{n:2,p:"Qual profeta viu o Senhor no alto e sublime trono?",o:["Ágabo","Isaías","Abacuque (Habacuque)","Obadias"],c:1,r:"Isaías 6:1"},
{n:2,p:"Qual profeta escreveu o livro de Lamentações?",o:["Elias","Miqueias","Malaquias","Jeremias"],c:3,r:"Lamentações"},
{n:2,p:"Qual profeta foi lançado na cova dos leões?",o:["Daniel","Jeremias","Zacarias","Jonas"],c:0,r:"Daniel 6:16"},
{n:2,p:"Qual profeta foi ordenado a casar com uma prostituta?",o:["Malaquias","Daniel","Oseias","Zacarias"],c:2,r:"Oseias 1:2"},
{n:2,p:"Qual profeta era boiadeiro e colhedor de figos bravos?",o:["Jeremias","Elias","Amós","Abacuque (Habacuque)"],c:2,r:"Amós 7:14"},
{n:2,p:"Qual profeta fugiu para Társis num navio?",o:["Oseias","Malaquias","Jonas","Miqueias"],c:2,r:"Jonas 1:3"},
{n:2,p:"Qual profeta profetizou que o Messias nasceria em Belém?",o:["Joel","Isaías","Oseias","Miqueias"],c:3,r:"Miqueias 5:2"},
{n:2,p:"Qual profeta falou sobre roubar a Deus nos dízimos?",o:["Joel","Malaquias","Daniel","Jeremias"],c:1,r:"Malaquias 3:8"},
{n:2,p:"Qual profeta profeta que amarrou o próprio cinto profetizando prisão a Paulo?",o:["Jeremias","Jonas","Isaías","Ágabo"],c:3,r:"Atos 21:11"},
{n:2,p:"Qual profeta profeta que repreendeu Davi com a parábola da ovelha?",o:["Ágabo","Obadias","Natã","Amós"],c:2,r:"2 Samuel 12:1"},
{n:2,p:"Qual igreja do Apocalipse era morna?",o:["Laodiceia","Éfeso","Filadélfia","Esmirna"],c:0,r:"Apocalipse 3:15-16"},
{n:2,p:"Qual jovem adormeceu e caiu da janela durante a pregação de Paulo?",o:["Êutico","Marcos","Pedro","Mateus"],c:0,r:"Atos 20:9"},
{n:2,p:"Em que cidade os discípulos foram chamados cristãos pela primeira vez?",o:["Belém","Sarepta","Éfeso","Antioquia"],c:3,r:"Atos 11:26"},
{n:2,p:"Qual foi a primeira igreja fundada na Europa?",o:["Transformou água em vinho","O arco-íris","Filipos","Isaque"],c:2,r:"Atos 16:12"},
{n:2,p:"Qual deusa era cultuada em Éfeso?",o:["Moisés","Pedro","Esdras","Diana (Ártemis)"],c:3,r:"Atos 19:28"},
{n:2,p:"Qual era o ofício de Paulo?",o:["Fazedores de tendas","Éden","Sara (Sarai)","Jessé"],c:0,r:"Atos 18:3"},
{n:2,p:"Em que ilha João escreveu o Apocalipse?",o:["Patmos","Sarepta","Belém","Atenas"],c:0,r:"Apocalipse 1:9"},
{n:2,p:"Qual centurião romano foi batizado por Pedro?",o:["Josué","Cornélio","Mateus","Jônatas"],c:1,r:"Atos 10:48"},
{n:2,p:"Qual judeu de Alexandria era poderoso nas Escrituras?",o:["Gamaliel","Neemias","Noé","Apolo"],c:3,r:"Atos 18:24"},
{n:2,p:"Qual vendedora de púrpura creu em Filipos?",o:["Natã","Lídia","Arão","Josué"],c:1,r:"Atos 16:14"},
{n:2,p:"Qual igreja do Apocalipse deixou o primeiro amor?",o:["Pérgamo","Tiatira","Éfeso","Esmirna"],c:2,r:"Apocalipse 2:4"},
{n:2,p:"Quem batizou o eunuco etíope?",o:["João","Abraão","Cornélio","Filipe"],c:3,r:"Atos 8:38"},
{n:2,p:"Qual chefe dos publicanos de Jericó recebeu Jesus em casa?",o:["Natã","Zorobabel","Zaqueu","Pedro"],c:2,r:"Lucas 19:2"},
{n:2,p:"De quem Jesus expulsou sete demônios?",o:["Saul","Maria Madalena","Malco","Zelofeade"],c:1,r:"Lucas 8:2"},
{n:2,p:"Qual discípulo é chamado o discípulo amado?",o:["João","Eliseu","Davi","Zorobabel"],c:0,r:"João 13:23"},
{n:2,p:"Qual fariseu procurou Jesus de noite?",o:["Barnabé","Cornélio","Davi","Nicodemos"],c:3,r:"João 3:1-2"},
{n:2,p:"Quem foi Simão, o cireneu?",o:["Zebedeu","Áquila","Ajudou Jesus a carregar a cruz","Simão Cireneu"],c:2,r:"Lucas 23:26"},
{n:2,p:"Quem foi escolhido para o lugar de Judas Iscariotes?",o:["Eva","José","Matias","Lameque"],c:2,r:"Atos 1:26"},
{n:2,p:"Quem era o sogro do sumo sacerdote Caifás?",o:["Ismael","Davi","Arão","Anás"],c:3,r:"João 18:13"},
{n:2,p:"Qual prisioneiro foi solto no lugar de Jesus?",o:["Barrabás","Jericó","Roma","Samaria"],c:0,r:"Mateus 27:26"},
{n:2,p:"Quem esteve preso com Paulo em Filipos?",o:["Cornélio","Silas","Jacó","Josué"],c:1,r:"Atos 16:25"},
{n:2,p:"Onde os discípulos foram chamados cristãos pela primeira vez?",o:["Antioquia","Baruque","Esaú","Tomé"],c:0,r:"Atos 11:26"},
{n:2,p:"Quem escreveu a maioria das cartas do Novo Testamento?",o:["Paulo","Lucas","Tércio","João"],c:0,r:"Novo Testamento"},
{n:2,p:"Qual era o nome da esposa de Abraão?",o:["Eunice","Sara (Sarai)","Miriã","Loide"],c:1,r:"Gênesis 17:15"},
{n:2,p:"Quem assumiu a liderança de Israel após a morte de Moisés?",o:["Paulo","Josué","Natã","Ananias"],c:1,r:"Josué 1:1-2"},
{n:2,p:"Qual mulher escondeu os espias israelitas em Jericó?",o:["Débora","Abigail","Mulher cananeia","Raabe"],c:3,r:"Josué 2:1"},
{n:2,p:"Qual era a profissão de Mateus antes de seguir a Cristo?",o:["Publicano","Dina","Pastor de ovelhas","Fazedor de tendas"],c:0,r:"Mateus 9:9"},
{n:2,p:"Quem foi o sucessor do profeta Elias?",o:["Adão","Zacarias","Amoz","Eliseu"],c:3,r:"2 Reis 2:9"},
{n:2,p:"Quem viu uma sarça ardente que não se consumia?",o:["Paulo","Moisés","Tiago","Samuel"],c:1,r:"Êxodo 3:2"},
{n:2,p:"Por quantos anos os israelitas vagaram pelo deserto?",o:["40 anos","41 anos","43 anos","39 anos"],c:0,r:"Josué 5:6"},
{n:2,p:"Qual apóstolo duvidou da ressurreição até tocar nas feridas de Jesus?",o:["Sete","Gamaliel","Tomé","Ananias"],c:2,r:"João 20:25"},
{n:2,p:"Que alimento Deus enviava do céu no deserto?",o:["Perfume","Cinto de couro","Maná","Lodo (barro)"],c:2,r:"Êxodo 16:15"},
{n:2,p:"Qual rei da Babilônia destruiu Jerusalém?",o:["Josias","Menaém","Nabucodonosor","Atalia"],c:2,r:"2 Reis 25:1"},
{n:2,p:"Quantos pães e peixes Jesus usou para alimentar 5.000 homens?",o:["5 pães e 2 peixes","Esdras","Noé","Tomé"],c:0,r:"Mateus 14:17"},
{n:2,p:"Quem ungiu os dois primeiros reis de Israel?",o:["Neemias","José","Moisés","Samuel"],c:3,r:"1 Samuel 10:1; 16:13"},
{n:2,p:"Quem sobreviveu à fornalha de fogo ardente?",o:["Abraão","Esaú","Timóteo","Sadraque, Mesaque e Abede-Nego"],c:3,r:"Daniel 3:26"},
{n:2,p:"De qual árvore Adão e Eva não podiam comer?",o:["Judá","Árvore do conhecimento do bem e do mal","Jericó","Benjamim"],c:1,r:"Gênesis 2:17"},
{n:2,p:"Quem ajudou Jesus a carregar a cruz?",o:["Simão, o cireneu","Absalão","Cornélio","Pedro"],c:0,r:"Lucas 23:26"},
{n:2,p:"Em que monte Jesus foi crucificado?",o:["Antioquia","Gólgota (Calvário)","Cesto","Carmelo"],c:1,r:"João 19:17"},
{n:2,p:"O que aconteceu com a mulher de Ló quando ela olhou para trás?",o:["Abraão foi sacrificar Isaque","Deus deu os Dez Mandamentos","Virou uma estátua de sal","Elias desafiou os profetas de Baal"],c:2,r:"Gênesis 19:26"},
{n:2,p:"Quem interpretou os sonhos de Faraó no Egito?",o:["Cornélio","José","Esaú","Filipe"],c:1,r:"Gênesis 41:25"},
{n:2,p:"Quais pássaros trouxeram alimento para o profeta Elias?",o:["Corvos","Barnabé","Tomé","Ananias"],c:0,r:"1 Reis 17:6"},
{n:2,p:"Onde Jesus foi preso antes da crucificação?",o:["Jônatas","Mateus","Jardim do Getsêmani","Davi"],c:2,r:"Mateus 26:36"},
{n:2,p:"Quem teve a visão de um vale de ossos secos?",o:["Ezequiel","Marcos","Labão","Esdras"],c:0,r:"Ezequiel 37:1-2"},
{n:2,p:"Quem era o mais velho dos doze filhos de Jacó?",o:["Judas (não Iscariotes)","Rúben","Filemom","Elcana"],c:1,r:"Gênesis 35:23"},
{n:2,p:"Quem libertou Pedro da prisão na véspera de sua execução?",o:["Um anjo do Senhor","Eliseu","Noé","Samuel"],c:0,r:"Atos 12:7"},

/* ---------- NÍVEL 3 — DIFÍCIL ---------- */
{n:3,p:"A quantas igrejas João escreve em Apocalipse 2 e 3?",o:["Quatro","Cinco","Sete","Doze"],c:2,r:"Apocalipse 1:11"},
{n:3,p:"Em qual rio Naamã mergulhou sete vezes e foi curado?",o:["Eufrates","Jordão","Nilo","Quebar"],c:1,r:"2 Reis 5:14"},
{n:3,p:"Qual escriba leu a Lei ao povo depois do exílio?",o:["Neemias","Esdras","Zorobabel","Ageu"],c:1,r:"Neemias 8:2-3"},
{n:3,p:"Qual rei de Judá recebeu mais quinze anos de vida?",o:["Josias","Ezequias","Manassés","Uzias"],c:1,r:"2 Reis 20:6"},
{n:3,p:"Quem era o pai do profeta Samuel?",o:["Eli","Elcana","Jeroboão","Abiatar"],c:1,r:"1 Samuel 1:1-20"},
{n:3,p:"Quais os nomes babilônicos dos três amigos de Daniel?",o:["Sadraque, Mesaque e Abede-Nego","Ananias, Misael e Azarias","Gogue, Magogue e Beltessazar","Hananias, Josadaque e Jeoiaquim"],c:0,r:"Daniel 1:7"},
{n:3,p:"Qual apóstolo era cobrador de impostos antes do chamado?",o:["Mateus","Tomé","Simão","Judas"],c:0,r:"Mateus 9:9"},
{n:3,p:"Quantos anos duraria o cativeiro babilônico, segundo Jeremias?",o:["40","50","70","400"],c:2,r:"Jeremias 25:11"},
{n:3,p:"Qual profeta menor tem um único capítulo?",o:["Ageu","Obadias","Naum","Sofonias"],c:1,r:"Obadias 1"},
{n:3,p:"Qual era a cidade natal de Abraão?",o:["Harã","Ur dos Caldeus","Damasco","Siquém"],c:1,r:"Gênesis 11:31"},
{n:3,p:"A quem o título do Salmo 90 atribui a autoria?",o:["Davi","Moisés","Asafe","Salomão"],c:1,r:"Salmo 90, título"},
{n:3,p:"Qual vendedora de púrpura se converteu em Filipos?",o:["Priscila","Lídia","Dorcas","Febe"],c:1,r:"Atos 16:14"},
{n:3,p:"Qual foi a décima e última praga do Egito?",o:["Trevas","Granizo","Morte dos primogênitos","Gafanhotos"],c:2,r:"Êxodo 12:29"},
{n:3,p:"Quem era o sumo sacerdote no julgamento de Jesus?",o:["Anás","Caifás","Gamaliel","Ananias"],c:1,r:"Mateus 26:57"},
{n:3,p:"Qual profeta alegou ser jovem demais para falar?",o:["Isaías","Jeremias","Ezequiel","Amós"],c:1,r:"Jeremias 1:6"},
{n:3,p:"Quais eram os nomes das irmãs de Lázaro?",o:["Marta e Maria","Ana e Joana","Salomé e Maria","Rute e Noemi"],c:0,r:"João 11:1-2"},
{n:3,p:"Qual rei viu a escrita misteriosa na parede do palácio?",o:["Nabucodonosor","Belsazar","Dario","Ciro"],c:1,r:"Daniel 5:5"},
{n:3,p:"Qual juiz fez um voto precipitado envolvendo sua filha?",o:["Gideão","Jefté","Sansão","Abimeleque"],c:1,r:"Juízes 11:30-31"},
{n:3,p:"Qual era o nome da serva egípcia, mãe de Ismael?",o:["Quetura","Agar","Zilpa","Bila"],c:1,r:"Gênesis 16:15"},
{n:3,p:"Qual rei mandou matar os meninos de Belém?",o:["Herodes","Arquelau","Agripa","Pilatos"],c:0,r:"Mateus 2:16"},
{n:3,p:"Qual é a mais curta das cartas de Paulo?",o:["Tito","Filemom","2 Tessalonicenses","Judas"],c:1,r:"Filemom, um só capítulo"},
{n:3,p:"Quem Pedro ressuscitou na cidade de Jope?",o:["Eutico","Dorcas (Tabita)","Enéias","Rode"],c:1,r:"Atos 9:36-40"},
{n:3,p:"Quantos anos Davi reinou sobre Israel?",o:["7","20","33","40"],c:3,r:"2 Samuel 5:4"},
{n:3,p:"Qual centurião de Cesareia foi batizado por Pedro?",o:["Cornélio","Júlio","Cláudio Lísias","Longino"],c:0,r:"Atos 10:1, 48"},
{n:3,p:"Como ficou conhecido o campo comprado com as trinta moedas?",o:["Campo de Boaz","Campo de Sangue","Campo do Semeador","Campo de Efrata"],c:1,r:"Mateus 27:8"},
{n:3,p:"Em que cidade Elias hospedou-se com uma viúva?",o:["Sarepta","Suném","Betel","Gilgal"],c:0,r:"1 Reis 17:9"},
{n:3,p:"Quantos filhos homens teve Jacó?",o:["7","10","12","14"],c:2,r:"Gênesis 35:22"},
{n:3,p:"Qual era o nome da mãe de João Batista?",o:["Ana","Isabel","Joana","Maria"],c:1,r:"Lucas 1:13"},
{n:3,p:"Em que monte Moisés recebeu as tábuas da Lei?",o:["Nebo","Sinai","Moriá","Sião"],c:1,r:"Êxodo 19:20"},
{n:3,p:"Quem foi o primeiro filho de Adão e Eva?",o:["Abel","Sete","Caim","Enos"],c:2,r:"Gênesis 4:1"},
{n:3,p:"Quem foi o avô de Davi?",o:["Otniel","Obede","Isaque","Áquila"],c:1,r:"Rute 4:22"},
{n:3,p:"Quem foi o filho de Enoque?",o:["Lameque","Nun","Matusalém","Zebedeu"],c:2,r:"Gênesis 5:21"},
{n:3,p:"Qual neto de Saul era aleijado dos pés?",o:["Mefibosete","Marcos","Filipe","Salomão"],c:0,r:"2 Samuel 4:4"},
{n:3,p:"Quem foi a bisavó de Davi?",o:["Rute","Eunice","Raabe","Ester"],c:0,r:"Rute 4:21-22"},
{n:3,p:"Quem foi a mãe de Timóteo?",o:["Eunice","Rute","Raabe","Ester"],c:0,r:"2 Timóteo 1:5"},
{n:3,p:"Quem foi a avó de Timóteo?",o:["Eunice","Débora","Filha de Herodias (Salomé)","Loide"],c:3,r:"2 Timóteo 1:5"},
{n:3,p:"De qual tribo Jesus descende?",o:["Judá","Árvore do conhecimento do bem e do mal","Benjamim","Jericó"],c:0,r:"Hebreus 7:14"},
{n:3,p:"De qual tribo era o apóstolo Paulo?",o:["Benjamim","Judá","Árvore do conhecimento do bem e do mal","Jericó"],c:0,r:"Romanos 11:1"},
{n:3,p:"Quem foi o pai de Noé?",o:["Lameque","Nun","Zebedeu","Amoz"],c:0,r:"Gênesis 5:28-29"},
{n:3,p:"Quem era o irmão de Tiago, autor da epístola?",o:["Jônatas","Lázaro","Judas (não Iscariotes)","Arão"],c:2,r:"Judas 1:1"},
{n:3,p:"Quem era o sumo sacerdote no ano em que Jesus morreu?",o:["Filemom","Lázaro","Caifás","Anás"],c:2,r:"João 11:49"},
{n:3,p:"Segundo a genealogia de Lucas, quem era o pai de José?",o:["Salomão","Eli","André","Barnabé"],c:1,r:"Lucas 3:23"},
{n:3,p:"Quem era o cunhado de Arão?",o:["Lázaro","Ismael","Caifás","Naassom"],c:3,r:"Êxodo 6:23"},
{n:3,p:"Qual juiz ou líder fez um voto precipitado que custou sua filha?",o:["Jair","Sansão","Jefté","Abdom"],c:2,r:"Juízes 11:30"},
{n:3,p:"Qual juiz de Israel era canhoto?",o:["Sansão","Eúde","Abdom","Abimeleque"],c:1,r:"Juízes 3:15"},
{n:3,p:"Qual rei de Moabe era muito gordo?",o:["Manassés","Ezequias","Menaém","Eglom"],c:3,r:"Juízes 3:17"},
{n:3,p:"Qual juiz ou líder matou Sísera com uma estaca?",o:["Jair","Jael","Abdom","Gideão"],c:1,r:"Juízes 4:21"},
{n:3,p:"Qual juiz ou líder matou 600 filisteus com uma aguilhada de boi?",o:["Sangar","Sansão","Abimeleque","Abdom"],c:0,r:"Juízes 3:31"},
{n:3,p:"Quem foi o primeiro juiz de Israel?",o:["Adão","Saul","Otniel","Estêvão"],c:2,r:"Juízes 3:9"},
{n:3,p:"Qual juiz ou líder fez a prova do velo de lã?",o:["Gideão","Abdom","Abimeleque","Sansão"],c:0,r:"Juízes 6:36"},
{n:3,p:"Qual juiz ou líder morto por uma pedra de moinho atirada por mulher?",o:["Sansão","Abdom","Abimeleque","Gideão"],c:2,r:"Juízes 9:53"},
{n:3,p:"Qual juiz ou líder tirou mel do cadáver de um leão?",o:["Gideão","Jefté","Jair","Sansão"],c:3,r:"Juízes 14:8"},
{n:3,p:"Qual juiz ou líder arrancou as portas de Gaza?",o:["Sansão","Abimeleque","Sangar","Jair"],c:0,r:"Juízes 16:3"},
{n:3,p:"Qual juiz ou líder tinha 30 filhos que montavam 30 jumentos?",o:["Sansão","Jair","Sangar","Abdom"],c:1,r:"Juízes 10:4"},
{n:3,p:"Qual juiz de Belém teve trinta filhos e trinta filhas?",o:["Ibzã","Abimeleque","Jefté","Sansão"],c:0,r:"Juízes 12:8-9"},
{n:3,p:"Qual juiz ou líder tinha 40 filhos e 30 netos montando jumentos?",o:["Sansão","Abdom","Jair","Gideão"],c:1,r:"Juízes 12:14"},
{n:3,p:"Quais reis midianitas Gideão matou?",o:["Apolo","Ananias","Zeba e Zalmuna","Sete"],c:2,r:"Juízes 8:21"},
{n:3,p:"Qual comandante lutou ao lado de Débora?",o:["Esaú","Natã","Barraque","José"],c:2,r:"Juízes 4:6"},
{n:3,p:"Qual rei de Israel que reinou apenas 7 dias?",o:["Menaém","Joás","Ezequias","Zinri"],c:3,r:"1 Reis 16:15"},
{n:3,p:"Qual rei na velhice sofreu dos pés mas não buscou a Deus?",o:["Ezequias","Joás","Acabe","Asa"],c:3,r:"2 Crônicas 16:12"},
{n:3,p:"Qual rei teve os olhos vazados e levado à Babilônia?",o:["Belsazar","Roboão","Assuero","Zedequias"],c:3,r:"2 Reis 25:7"},
{n:3,p:"Qual rei de Israel/Judá/Pérsia O rei de Israel considerado o mais iníquo antes dele?",o:["Menaém","Atalia","Acabe","Hoshea (Oseias)"],c:2,r:"1 Reis 21:25"},
{n:3,p:"Qual rei de Judá que começou a reinar aos 7 anos?",o:["Joás","Atalia","Menaém","Manassés"],c:0,r:"2 Crônicas 24:1"},
{n:3,p:"Qual rei de Israel/Judá/Pérsia Rainha que usurpou o trono de Judá matando a descendência?",o:["Menaém","Atalia","Acabe","Hoshea (Oseias)"],c:1,r:"2 Reis 11:1"},
{n:3,p:"Qual rei banqueteou com as taças do templo e viu a mão?",o:["Menaém","Belsazar","Artaxerxes","Herodes, o Grande"],c:1,r:"Daniel 5:1-5"},
{n:3,p:"Qual rei assinou o decreto que jogou Daniel aos leões?",o:["Uzias","Joás","Ezequias","Dario"],c:3,r:"Daniel 6:9"},
{n:3,p:"Qual rei de Judá que reinou 55 anos, o mais longo?",o:["Zinri","Atalia","Ezequias","Manassés"],c:3,r:"2 Reis 21:1"},
{n:3,p:"Qual rei comprou o monte e edificou Samaria?",o:["Manassés","Belsazar","Ezequias","Onri"],c:3,r:"1 Reis 16:24"},
{n:3,p:"Qual rei dirigia o carro furiosamente?",o:["Jeú","Dario","Manassés","Atalia"],c:0,r:"2 Reis 9:20"},
{n:3,p:"Qual rei de Israel/Judá/Pérsia Rasgou o ventre das mulheres grávidas de Tifsa?",o:["Hoshea (Oseias)","Menaém","Acabe","Atalia"],c:1,r:"2 Reis 15:16"},
{n:3,p:"Qual rei de Israel/Judá/Pérsia Último rei do reino do Norte (Israel)?",o:["Atalia","Hoshea (Oseias)","Acabe","Menaém"],c:1,r:"2 Reis 17:1"},
{n:3,p:"Qual rei atingido com lepra na testa no templo?",o:["Atalia","Onri","Uzias","Jeroboão"],c:2,r:"2 Crônicas 26:19"},
{n:3,p:"Qual rei para quem Neemias era copeiro?",o:["Acabe","Herodes, o Grande","Artaxerxes","Eglom"],c:2,r:"Neemias 2:1"},
{n:3,p:"Com quantos anos Moisés morreu?",o:["120 anos","110 anos","119 anos","121 anos"],c:0,r:"Deuteronômio 34:7"},
{n:3,p:"Por quantos dias Ezequiel deitou sobre o lado esquerdo?",o:["350 dias","389 dias","390 dias","195 dias"],c:2,r:"Ezequiel 4:5"},
{n:3,p:"Quantos profetas de Baal Elias enfrentou no Carmelo?",o:["450","451","453","447"],c:0,r:"1 Reis 18:22"},
{n:3,p:"Quantos salmos tem o livro de Salmos?",o:["151","150","250","149"],c:1,r:"Livro de Salmos"},
{n:3,p:"Quantos capítulos tem o livro de Isaías?",o:["63","132","69","66"],c:3,r:"Livro de Isaías"},
{n:3,p:"Quantas virgens prudentes há na parábola das dez virgens?",o:["5","6","8","4"],c:0,r:"Mateus 25:2"},
{n:3,p:"Quantos peixes os discípulos pescaram depois da ressurreição?",o:["76","253","150","153"],c:3,r:"João 21:11"},
{n:3,p:"Qual era o comprimento da arca de Noé?",o:["400 côvados","300 côvados","600 côvados","293 côvados"],c:1,r:"Gênesis 6:15"},
{n:3,p:"Quanto ouro Salomão recebia por ano?",o:["666 talentos","706 talentos","766 talentos","656 talentos"],c:0,r:"1 Reis 10:14"},
{n:3,p:"Quantas raposas Sansão capturou?",o:["300","290","600","900"],c:0,r:"Juízes 15:4"},
{n:3,p:"Por quanto José foi vendido pelos irmãos?",o:["13 siclos de prata","17 siclos de prata","30 siclos de prata","20 siclos de prata"],c:3,r:"Gênesis 37:28"},
{n:3,p:"Por quantos anos Enoque andou com Deus depois de gerar Matusalém?",o:["300 anos","290 anos","301 anos","260 anos"],c:0,r:"Gênesis 5:22"},
{n:3,p:"Quantas vezes Lameque disse que seria vingado?",o:["77","78","154","84"],c:0,r:"Gênesis 4:24"},
{n:3,p:"Quantos anos Jacó serviu ao todo por Raquel?",o:["7","21","14","24"],c:2,r:"Gênesis 31:41"},
{n:3,p:"Qual nome bíblico significa 'Deus conosco'?",o:["Emanuel","Barnabé","Cefas (Pedro)","Babel"],c:0,r:"Mateus 1:23"},
{n:3,p:"Qual nome bíblico significa 'Tirado das águas'?",o:["Betel","Abraão","Jesus (Yeshua)","Moisés"],c:3,r:"Êxodo 2:10"},
{n:3,p:"Qual nome bíblico significa 'Riso'?",o:["Moisés","Babel","Sara","Isaque"],c:3,r:"Gênesis 21:6"},
{n:3,p:"Qual nome bíblico significa 'Pedra'?",o:["Gólgota","Cefas (Pedro)","Emanuel","Melquisedeque"],c:1,r:"João 1:42"},
{n:3,p:"Qual nome bíblico significa 'Pai de multidões'?",o:["Abraão","Melquisedeque","Emanuel","Mara"],c:0,r:"Gênesis 17:5"},
{n:3,p:"Qual nome bíblico significa 'Princesa'?",o:["Betel","Gólgota","Abraão","Sara"],c:3,r:"Gênesis 17:15"},
{n:3,p:"Qual nome bíblico significa 'Casa de Deus'?",o:["Barnabé","Peniel","Betel","Babel"],c:2,r:"Gênesis 28:19"},
{n:3,p:"Qual nome bíblico significa 'Face de Deus'?",o:["Peniel","Abraão","Emanuel","Babel"],c:0,r:"Gênesis 32:30"},
{n:3,p:"Qual nome bíblico significa 'Amargura'?",o:["Benoni","Betel","Mara","Emanuel"],c:2,r:"Êxodo 15:23"},
{n:3,p:"Qual nome bíblico significa 'Confusão'?",o:["Emanuel","Babel","Melquisedeque","Abraão"],c:1,r:"Gênesis 11:9"},
{n:3,p:"Qual nome bíblico significa 'Rei de justiça'?",o:["Benoni","Jesus (Yeshua)","Emanuel","Melquisedeque"],c:3,r:"Hebreus 7:2"},
{n:3,p:"Qual nome bíblico significa 'Filho da minha dor'?",o:["Benoni","Barnabé","Peniel","Emanuel"],c:0,r:"Gênesis 35:18"},
{n:3,p:"Qual nome bíblico significa 'Filho da consolação'?",o:["Gólgota","Jesus (Yeshua)","Moisés","Barnabé"],c:3,r:"Atos 4:36"},
{n:3,p:"Qual nome bíblico significa 'Lugar da caveira'?",o:["Gólgota","Jesus (Yeshua)","Melquisedeque","Isaque"],c:0,r:"João 19:17"},
{n:3,p:"Qual nome bíblico significa 'Salvo ou Salvador'?",o:["Jesus (Yeshua)","Benoni","Sara","Emanuel"],c:0,r:"Mateus 1:21"},
{n:3,p:"Que dois sinais tornavam um animal puro na lei de Moisés?",o:["Madeira de gofer","Vara de Arão","Cinto de couro","Fendido o casco e ruminante"],c:3,r:"Levítico 11:3"},
{n:3,p:"De quantos em quantos anos se celebrava o Jubileu?",o:["Ano 50","Samuel","Abraão","Jacó"],c:0,r:"Levítico 25:11"},
{n:3,p:"Quantas pedras havia no peitoral do sumo sacerdote?",o:["Quatro","Doze","Três","Cinco"],c:1,r:"Êxodo 28:21"},
{n:3,p:"Que objetos o sumo sacerdote usava para consultar a Deus?",o:["Espada","Urim e Tumim","Vara de Arão","Cântaros e tochas"],c:1,r:"Êxodo 28:30"},
{n:3,p:"Como se chama o Dia da Expiação?",o:["Jacó","Mateus","Yom Kippur","Barnabé"],c:2,r:"Levítico 23:27"},
{n:3,p:"Qual tribo não recebeu herança de terra em Canaã?",o:["Naftali","Simeão","Judá","Levitas"],c:3,r:"Josué 13:33"},
{n:3,p:"Quantas cidades de refúgio foram estabelecidas?",o:["Quatro","Cinco","Três","Seis"],c:3,r:"Números 35:13"},
{n:3,p:"Que voto proibia cortar o cabelo e beber vinho?",o:["Estrela","Pedra de moinho","Cinto de couro","Nazireu"],c:3,r:"Números 6:2-5"},
{n:3,p:"O que era guardado dentro da arca da aliança?",o:["Maná, vara de Arão, tábuas da lei","Virou uma estátua de sal","Moisés avistou a Terra Prometida e morreu","Deus falou na sarça ardente a Moisés"],c:0,r:"Hebreus 9:4"},
{n:3,p:"Quem tocou na arca da aliança e morreu?",o:["Apolo","Uzá","Josué","Pedro"],c:1,r:"2 Samuel 6:7"},
{n:3,p:"Quais filhos de Arão morreram ao oferecer fogo estranho?",o:["Cornélio","Filipe","Jônatas","Nadabe e Abiú"],c:3,r:"Levítico 10:1-2"},
{n:3,p:"Qual era a pena para a blasfêmia na lei de Moisés?",o:["Copeiro do rei","Apedrejamento","Dina","Pastor de ovelhas"],c:1,r:"Levítico 24:16"},
{n:3,p:"Qual povo enganou Josué fingindo vir de terra distante?",o:["Harã","Gibeonitas","Hebrom","Betel"],c:1,r:"Josué 9:4"},
{n:3,p:"De quem eram as cinco filhas que pediram herança a Moisés?",o:["Maria Madalena","Zelofeade","Samuel","Absalão"],c:1,r:"Números 27:1"},
{n:3,p:"Em qual sacrifício o ofertante comia parte da carne?",o:["Oferta pacífica","Parábola do Bom Samaritano","Belém","Parábola das Dez Virgens"],c:0,r:"Levítico 3"},
{n:3,p:"Quem escreveu a carta aos Romanos como secretário de Paulo?",o:["Tércio","João","Lucas","Apóstolo Paulo"],c:0,r:"Romanos 16:22"},
{n:3,p:"Por qual escravo fugitivo Paulo intercedeu numa carta?",o:["Sete","Onésimo","João","Absalão"],c:1,r:"Filemom 1:10"},
{n:3,p:"Quem era o dono do escravo Onésimo?",o:["Elcana","Filemom","Caifás","Rúben"],c:1,r:"Filemom 1:1"},
{n:3,p:"Quem Paulo deixou em Creta para organizar as igrejas?",o:["Marcos","Tito","Abraão","Timóteo"],c:1,r:"Tito 1:5"},
{n:3,p:"Como Paulo se referia a Lucas?",o:["João","Gideão","Arão","Médico amado"],c:3,r:"Colossenses 4:14"},
{n:3,p:"Em que cidade ficava o templo de Diana?",o:["Jericó","Belém","Éfeso","Antioquia"],c:2,r:"Atos 19:27"},
{n:3,p:"Em que cidade Paulo viu o altar ao Deus desconhecido?",o:["Sarepta","Atenas","Antioquia","Éfeso"],c:1,r:"Atos 17:23"},
{n:3,p:"Qual ourives provocou o tumulto em Éfeso?",o:["Paulo","Boaz","Demétrio","Gideão"],c:2,r:"Atos 19:24"},
{n:3,p:"Qual carta afirma que a fé sem obras é morta?",o:["Tiago","Mateus","Efésios","Levítico"],c:0,r:"Tiago 2:26"},
{n:3,p:"Qual carta traz a galeria dos heróis da fé?",o:["Gênesis","Tito","Hebreus","Romanos"],c:2,r:"Hebreus 11"},
{n:3,p:"Quem escreveu o Apocalipse estando exilado em Patmos?",o:["João","Apóstolo Paulo","Tércio","Lucas"],c:0,r:"Apocalipse 1:9"},
{n:3,p:"Qual igreja do Apocalipse tinha nome de que vivia, mas estava morta?",o:["Filadélfia","Tiatira","Sardes","Esmirna"],c:2,r:"Apocalipse 3:1"},
{n:3,p:"Diante de qual igreja Jesus pôs uma porta aberta?",o:["Filadélfia","Pérgamo","Éfeso","Esmirna"],c:0,r:"Apocalipse 3:8"},
{n:3,p:"Quais obras a igreja de Éfeso aborrecia?",o:["Tomé","Gamaliel","Silas","Nicolaítas"],c:3,r:"Apocalipse 2:6"},
{n:3,p:"Em qual carta Paulo diz que já não é ele quem vive, mas Cristo?",o:["Parábola das Dez Virgens","Belém","Gálatas","Getsêmani"],c:2,r:"Gálatas 2:20"},
{n:3,p:"Qual profeta andou nu e descalço por três anos?",o:["Miqueias","Isaías","Eliseu","Ágabo"],c:1,r:"Isaías 20:3"},
{n:3,p:"Qual profeta viu as rodas cheias de olhos?",o:["Ezequiel","Eliseu","Natã","Jeremias"],c:0,r:"Ezequiel 1:16"},
{n:3,p:"Qual profeta chamou sua filha de Lo-Ruama?",o:["Oseias","Elias","Amós","Jeremias"],c:0,r:"Oseias 1:6"},
{n:3,p:"Qual profeta escreveu inteiramente contra Edom?",o:["Obadias","Ágabo","Zacarias","Eliseu"],c:0,r:"Obadias 1:1"},
{n:3,p:"Qual profeta anunciou o Espírito derramado sobre toda a carne?",o:["Joel","Jeremias","Isaías","Zacarias"],c:0,r:"Joel 2:28"},
{n:3,p:"O que Daniel viu subir do mar em sua visão?",o:["Abraão foi sacrificar Isaque","Cântaros e tochas","Quatro bestas","Duas moedinhas"],c:2,r:"Daniel 7:3"},
{n:3,p:"O que Nabucodonosor sonhou e Daniel interpretou?",o:["Abraão foi sacrificar Isaque","Aconteceu a Transfiguração de Jesus","Estátua de 4 metais e barro","Deus falou na sarça ardente a Moisés"],c:2,r:"Daniel 2:31"},
{n:3,p:"Qual arcanjo disputou o corpo de Moisés?",o:["Miguel","Cornélio","André","Ananias"],c:0,r:"Judas 1:9"},
{n:3,p:"Que nações Satanás engana no fim, segundo o Apocalipse?",o:["Filisteus","Assírios","Gibeonitas","Gogue e Magogue"],c:3,r:"Apocalipse 20:8"},
{n:3,p:"Qual profeta anunciou que o Messias nasceria em Belém?",o:["Ágabo","Elias","Zacarias","Miqueias"],c:3,r:"Miqueias 5:2"},
{n:3,p:"Qual profeta viu o castiçal de ouro e as duas oliveiras?",o:["Zacarias","Malaquias","Eliseu","Abacuque (Habacuque)"],c:0,r:"Zacarias 4:2-3"},
{n:3,p:"Qual profeta anunciou a vinda do profeta Elias?",o:["Malaquias","Amós","Daniel","Abacuque (Habacuque)"],c:0,r:"Malaquias 4:5"},
{n:3,p:"Qual profeta escreveu que o justo viverá pela fé?",o:["Abacuque (Habacuque)","Ágabo","Zacarias","Miqueias"],c:0,r:"Habacuque 2:4"},
{n:3,p:"Qual profeta comprou um campo em Anatote durante o cerco?",o:["Miqueias","Jeremias","Elias","Jonas"],c:1,r:"Jeremias 32:9"},
{n:3,p:"Qual patriarca é citado em Judas profetizando a vinda do Senhor?",o:["Isaque","Apolo","Enoque","Barnabé"],c:2,r:"Judas 1:14"},
{n:3,p:"Qual rei viu a escrita na parede?",o:["Belsazar","Ezequias","Rei Asa","Ciro"],c:0,r:"Daniel 5:5"},
{n:3,p:"Qual profeta casou-se com uma prostituta por ordem divina?",o:["Joel","Malaquias","Oseias","Zacarias"],c:2,r:"Oseias 1:2"},
{n:3,p:"Quem matou o general Sísera com uma estaca de tenda?",o:["Timóteo","Isaque","Ló","Jael"],c:3,r:"Juízes 4:21"},
{n:3,p:"Quem foi o homem que viveu mais tempo na terra?",o:["Lameque","Estêvão","Moisés","Matusalém"],c:3,r:"Gênesis 5:27"},
{n:3,p:"Com quantos anos morreu Matusalém?",o:["979 anos","969 anos","484 anos","976 anos"],c:1,r:"Gênesis 5:27"},
{n:3,p:"Qual rei de Moabe era conhecido por ser muito gordo?",o:["Hoshea (Oseias)","Eglom","Manassés","Joás"],c:1,r:"Juízes 3:17"},
{n:3,p:"Qual juiz canhoto matou o rei Eglom?",o:["Jair","Sansão","Sangar","Eúde"],c:3,r:"Juízes 3:21"},
{n:3,p:"A qual tribo de Israel pertencia o rei Saul?",o:["Tribo de Benjamim","Issacar","Zebulom","Manassés"],c:0,r:"1 Samuel 9:1-2"},
{n:3,p:"Onde o apóstolo João estava quando escreveu o Apocalipse?",o:["Gideão","André","Silas","Na ilha de Patmos"],c:3,r:"Apocalipse 1:9"},
{n:3,p:"Qual era o nome da mãe de Timóteo?",o:["Loide","Miriã","Maria","Eunice"],c:3,r:"2 Timóteo 1:5"},
{n:3,p:"Qual era o nome da avó de Timóteo?",o:["Agar","Loide","Sara (Sarai)","Eunice"],c:1,r:"2 Timóteo 1:5"},
{n:3,p:"De quem foi o cadáver que ressuscitou ao tocar nos ossos de Eliseu?",o:["Zelofeade","Maria Madalena","Samuel","De um israelita anônimo"],c:3,r:"2 Reis 13:21"},
{n:3,p:"Que rei orou e teve 15 anos adicionados à sua vida?",o:["Dario","Nabucodonosor","Salomão","Ezequias"],c:3,r:"2 Reis 20:6"},
{n:3,p:"Qual sacerdote caiu da cadeira, quebrou o pescoço e morreu?",o:["Eli","Filipe","Abraão","Timóteo"],c:0,r:"1 Samuel 4:18"},
{n:3,p:"Quem foi o rei de Israel que teve os olhos vazados pelos filisteus?",o:["Boaz","Jacó","Estêvão","Zedequias"],c:3,r:"2 Reis 25:7"},
{n:3,p:"Qual era o nome original do patriarca Abraão?",o:["Jessé","Abrão","Maria","Sara (Sarai)"],c:1,r:"Gênesis 17:5"},
{n:3,p:"Quem profetizou sobre um vale cheio de ossos secos que ganharam vida?",o:["Neemias","Eliseu","Apolo","Ezequiel"],c:3,r:"Ezequiel 37:1"},
{n:3,p:"Quem chamou os fariseus de 'raça de víboras'?",o:["Absalão","Esaú","Samuel","João Batista"],c:3,r:"Mateus 3:7"},
{n:3,p:"Qual profeta era um boiadeiro e cultivador de figos antes de seu chamado?",o:["Joel","Amós","Ágabo","Jeremias"],c:1,r:"Amós 7:14"},
{n:3,p:"Quem se disfarçou para consultar a médium de En-Dor?",o:["Gamaliel","Labão","Rei Saul","Esaú"],c:2,r:"1 Samuel 28:8"},
{n:3,p:"Quem era a deusa dos efésios que causou tumulto contra Paulo?",o:["Raquel","Miriã","Maria","Diana (Ártemis)"],c:3,r:"Atos 19:28"},
{n:3,p:"Qual o nome do sumo sacerdote na época do julgamento de Jesus?",o:["Tomé","Caifás","Josué","Ló"],c:1,r:"Mateus 26:3"},
{n:3,p:"Quem escondeu cem profetas em cavernas para protegê-los de Jezabel?",o:["João","Ananias","José","Obadias"],c:3,r:"1 Reis 18:4"},
{n:3,p:"Qual rei adoeceu gravemente e teve seus pés afetados pela doença?",o:["Rei Asa","Ciro","Menaém","Manassés"],c:0,r:"2 Crônicas 16:12"},
{n:3,p:"O apóstolo Paulo era da descendência de qual tribo de Israel?",o:["Rúben","Simeão","Tribo de Benjamim","Gade"],c:2,r:"Filipenses 3:5"},
{n:3,p:"Qual rei teve como punição viver como um animal do campo?",o:["Nabucodonosor","Rei Asa","Zinri","Salomão"],c:0,r:"Daniel 4:33"},
{n:3,p:"Quem reconstruiu os muros de Jerusalém em apenas 52 dias?",o:["Mateus","Arão","Eliseu","Neemias"],c:3,r:"Neemias 6:15"},
{n:3,p:"Que servo perdeu a audição temporariamente, após o sumo sacerdote rasgar suas roupas?",o:["Mateus","Cornélio","Zacarias (pai de João Batista)","Boaz"],c:2,r:"Lucas 1:20"},
{n:3,p:"Quem escreveu a carta aos Romanos?",o:["Apóstolo Paulo","Lucas","João","Tércio"],c:0,r:"Romanos 1:1"},
{n:3,p:"Quem escreveu a carta aos 1 Coríntios?",o:["Apóstolo Paulo","João","Tércio","Lucas"],c:0,r:"1 Coríntios 1:1"},
{n:3,p:"Quem escreveu a carta aos Gálatas?",o:["Tércio","João","Lucas","Apóstolo Paulo"],c:3,r:"Gálatas 1:1"},
{n:3,p:"Quem escreveu a carta aos Efésios?",o:["João","Lucas","Apóstolo Paulo","Tércio"],c:2,r:"Efésios 1:1"},
{n:3,p:"Quem escreveu a carta aos Filipenses?",o:["Tércio","Lucas","João","Apóstolo Paulo"],c:3,r:"Filipenses 1:1"},
{n:3,p:"Quem escreveu a carta aos Colossenses?",o:["Lucas","Apóstolo Paulo","João","Tércio"],c:1,r:"Colossenses 1:1"},
{n:3,p:"Quem escreveu a carta aos 1 Tessalonicenses?",o:["Apóstolo Paulo","João","Tércio","Lucas"],c:0,r:"1 Tessalonicenses 1:1"},
{n:3,p:"Quem escreveu a carta aos 1 Timóteo?",o:["João","Lucas","Apóstolo Paulo","Tércio"],c:2,r:"1 Timóteo 1:1"},
{n:3,p:"Quem escreveu a carta aos Tito?",o:["Apóstolo Paulo","Tércio","João","Lucas"],c:0,r:"Tito 1:1"},
{n:3,p:"Quem escreveu a carta aos Filemom?",o:["Lucas","João","Apóstolo Paulo","Tércio"],c:2,r:"Filemom 1:1"}
];

const NOME_NIVEL = {1:"Nível fácil", 2:"Nível médio", 3:"Nível difícil"};
const ACERTO_MAQUINA = {1:0.50, 2:0.72, 3:0.88};

/* Sorteia sem repetir. Quando o nível esgota, ele recomeça sozinho. */
const Banco = {
  usadas: [],
  sortear(nivel){
    let pool = PERGUNTAS.map((q,i) => ({q,i})).filter(x => x.q.n === nivel && !this.usadas.includes(x.i));
    if(pool.length === 0){
      this.usadas = this.usadas.filter(i => PERGUNTAS[i].n !== nivel);
      pool = PERGUNTAS.map((q,i) => ({q,i})).filter(x => x.q.n === nivel);
    }
    const escolhida = pool[Math.floor(Math.random() * pool.length)];
    this.usadas.push(escolhida.i);
    return escolhida.q;
  },
  zerar(){ this.usadas = []; },
  quantas(nivel){ return PERGUNTAS.filter(q => q.n === nivel).length; }
};
